ALTER TABLE CHROMOSOME DROP CONSTRAINT  "FK_CHRO_TO_TAX"
ALTER TABLE CHROMOSOME ADD CONSTRAINT  "FK_CHRO_TO_TAX" FOREIGN KEY  (TAXONOMY_TREE_ID) REFERENCES TAXONOMY_TREE_NEW (TAXONOMY_TREE_ID) ON DELETE CASCADE
ALTER TABLE UN_ENTRY DROP CONSTRAINT "FK_UN_ENTRY_TO_TAX_ID"
ALTER TABLE UN_ENTRY ADD CONSTRAINT  "FK_UN_ENTRY_TO_TAX_ID" FOREIGN KEY  (TAXONOMY_TREE_ID) REFERENCES TAXONOMY_TREE_NEW (TAXONOMY_TREE_ID) ON DELETE CASCADE
ALTER TABLE PW_ENTRY DROP CONSTRAINT "FK_PWE_TAX"
ALTER TABLE PW_ENTRY ADD CONSTRAINT "FK_PWE_TAX" FOREIGN KEY (TAXONOMY_TREE_ID) REFERENCES TAXONOMY_TREE_NEW (TAXONOMY_TREE_ID) ON DELETE CASCADE
CALL PROC_DEL_TBL('TAXONOMY_TREE_PREV')
ALTER TABLE TAXONOMY_TREE RENAME TO TAXONOMY_TREE_PREV
ALTER TABLE TAXONOMY_TREE_NEW RENAME TO TAXONOMY_TREE
ALTER TABLE TAXONOMY_TREE_PREV RENAME CONSTRAINT "PK_TAXO_TAX_TREE_ID" TO "PK_TAXO_TAX_TREE_ID_PREV"
ALTER INDEX PK_TAXO_TAX_TREE_ID RENAME TO PK_TAXO_TAX_TREE_ID_PREV
ALTER INDEX TAXONOMY_TREE_INDEX1 RENAME TO TAXONOMY_TREE_INDEX1_PREV
ALTER INDEX TAXONOMY_TREE_INDEX2 RENAME TO TAXONOMY_TREE_INDEX2_PREV
ALTER INDEX TAXONOMY_TREE_INDEX3 RENAME TO TAXONOMY_TREE_INDEX3_PREV
ALTER INDEX PK_TAXO_TAX_TREE_ID_NEW RENAME TO PK_TAXO_TAX_TREE_ID
ALTER TABLE TAXONOMY_TREE RENAME CONSTRAINT PK_TAXO_TAX_TREE_ID_NEW TO PK_TAXO_TAX_TREE_ID
CREATE INDEX "TAXONOMY_TREE_INDEX1" ON TAXONOMY_TREE("TAX_LEVEL")
CREATE INDEX "TAXONOMY_TREE_INDEX2" ON TAXONOMY_TREE("LEVEL_LEFT", "LEVEL_RIGHT")
CREATE UNIQUE INDEX "TAXONOMY_TREE_INDEX3" ON TAXONOMY_TREE("TAX_ID")
