CREATE TABLE \"XRAY2_OWNER\".\"TAXONOMY_TREE_NEW\"
(	\"TAXONOMY_TREE_ID\" NUMBER(19,0) NOT NULL ENABLE, 
	\"TAX_LEVEL\" NUMBER(5,0), 
	\"LEVEL_LEFT\" NUMBER(9,0), 
	\"LEVEL_RIGHT\" NUMBER(9,0), 
	\"SCIENTIFIC_NAME\" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	\"TAX_ID\" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	\"RANK\" VARCHAR2(30 CHAR) DEFAULT NULL,
        \"DATE_CREATED\" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
        \"DATE_UPDATED\" TIMESTAMP (6) DEFAULT NULL,
        CONSTRAINT \"PK_TAXO_TAX_TREE_ID_NEW\" PRIMARY KEY (\"TAXONOMY_TREE_ID\")
)
