ALTER TABLE MV_GENE_PUBLI_NEW RENAME TO MV_GENE_PUBLI
CREATE INDEX MV_GENE_PUBLI_IDX1 ON MV_GENE_PUBLI (GN_ENTRY_ID,PUBLICATION_DATE)
CREATE INDEX MV_GENE_PUBLI_IDX2 ON MV_GENE_PUBLI (GN_ENTRY_ID,PMID)
