CREATE TABLE MV_GENE_PUBLI_NEW AS SELECT GN_ENTRY_ID,PE.PMID_ENTRY_ID,PMID,PUBLICATION_DATE
FROM PMID_ENTRY PE, PMID_GENE_MAP PGM
WHERE PGM.PMID_ENTRY_ID = PE.PMID_ENTRY_ID ORDER BY GN_ENTRY_ID ASC,PUBLICATION_DATE DESC
