ALTER TABLE MV_GENE_SP_NEW RENAME TO MV_GENE_SP
CREATE INDEX MV_GENE_SP_INDEX3 ON MV_GENE_SP (GN_ENTRY_ID) 
CREATE INDEX MV_GENE_SP_INDEX4 ON MV_GENE_SP (TAX_ID) 
CREATE INDEX MV_GENE_SP_INDEX1 ON MV_GENE_SP (SYMBOL) 
CREATE INDEX MV_GENE_SP_INDEX2 ON MV_GENE_SP (GENE_ID)
CREATE INDEX MV_GENE_SP_INDEX5 ON MV_GENE_SP (SYN_VALUE)
