ALTER TABLE MV_GENE_NEW RENAME TO MV_GENE
CREATE MATERIALIZED VIEW MV_GENE (SYMBOL, FULL_NAME, GENE_ID, GN_ENTRY_ID, SYN_VALUE, SCIENTIFIC_NAME, TAX_ID) ON PREBUILT TABLE NEVER REFRESH AS Select symbol,full_name,gene_id, gn.gn_entry_id, syn_value, scientific_name, tax_id From Taxonomy_Tree Tt  Right Join Chromosome Ch On Ch.Taxonomy_Tree_Id = Tt.Taxonomy_Tree_Id Full Outer Join Chr_Map Cm On Cm.Chr_Id = Ch.Chr_Id  Full Outer Join Chr_Gn_Map Cgm On Cgm.Chr_Map_Id = Cm.Chr_Map_Id Full Outer Join Gn_Entry Gn On Cgm.Gn_Entry_Id = Gn.Gn_Entry_Id  FULL OUTER JOIN (SELECT SYN_VALUE, GN_ENTRY_ID FROM GN_SYN GS, GN_SYN_MAP GSM WHERE GS.GN_SYN_ID=GSM.GN_SYN_ID AND SYN_TYPE='S') S ON S.GN_ENTRY_ID = GN.GN_ENTRY_ID
CREATE INDEX MV_GENE_INDEX3 ON MV_GENE (GN_ENTRY_ID) 
CREATE INDEX MV_GENE_INDEX4 ON MV_GENE (TAX_ID) 
CREATE INDEX MV_GENE_INDEX1 ON MV_GENE (SYMBOL) 
CREATE INDEX MV_GENE_INDEX2 ON MV_GENE (GENE_ID)
