<?php

/**
 SCRIPT NAME: db_gtex_stat
 PURPOSE:     Push basic statistics per gene and transcript against tissues in the database
 
*/

/// Job name - Do not change
$JOB_NAME='db_gtex_stat';


/// Get root directories
$TG_DIR= getenv('TG_DIR');
if ($TG_DIR===false)  die('NO TG_DIR found ');
if (!is_dir($TG_DIR)) die('TG_DIR value is not a directory '.$TG_DIR);
require_once($TG_DIR.'/BACKEND/SCRIPT/LIB/loader.php');

/// Get job id
$JOB_ID=getJobIDByName($JOB_NAME);
$PROCESS_CONTROL['DIR']='N/A';
/// Get job info
$JOB_INFO=$GLB_TREE[$JOB_ID];



addLog("Check directory");
	/// Get Parent info
	$CK_INFO=$GLB_TREE[getJobIDByName('rmj_gtex')];
	
	/// Get to working directory
	$W_DIR=$TG_DIR.'/'.$GLB_VAR['PROCESS_DIR'].'/'.$JOB_INFO['DIR'].'/'.$CK_INFO['TIME']['DEV_DIR'];	
	if (!is_dir($W_DIR))															failProcess($JOB_ID."001",'NO '.$W_DIR.' found ');
	if ( !chdir($W_DIR))															failProcess($JOB_ID."002",'Unable to access '.$W_DIR);

	/// Update the process control so that the next job can access the directory
	$PROCESS_CONTROL['DIR']=$CK_INFO['TIME']['DEV_DIR'];

	

addLog("Static file check");
	/// This script will take as input the results generated by process_gtex and push them in the database
	/// process_gtex compute statistics at the gene and transcript level
	/// so we are getting the max PK id for those tables
	$DBIDS=array('rna_gene_stat'=>-1,'rna_transcript_stat'=>-1);
	foreach ($DBIDS as $TBL=>$CTL)
	{
		$res=runQuery("SELECT MAX(".$TBL.'_ID) CO FROM '.$TBL);
		if ($res===false)															failProcess($JOB_ID."003",'Unable to get Max ID for '.$TBL);
		$DBIDS[$TBL]=(count($res)==1)?$res[0]['co']:0;
		
	
	}

	///	And create a file for each
	$fpO=fopen('ALL_STAT_GENE.csv','w');if (!$fpO)										failProcess($JOB_ID."004",'Unable to open ALL_STAT.csv');
	$fpT=fopen('ALL_STAT_TR.csv','w');if (!$fpT)										failProcess($JOB_ID."005",'Unable to open ALL_STAT_TR.csv');
addLog("Merge Files");

	/// There's 200 scripts run in parallel, each of them creating a result file
	for($I=1;$I<=200;++$I)
	{
		if (!checkFileExist('RESULTS_'.$I.'.csv'))									failProcess($JOB_ID."006",'Missing RESULTS_'.$I.' file ');
		/// So we read the file
		$fp=fopen($W_DIR.'/RESULTS_'.$I.'.csv','r');if (!$fp)						failProcess($JOB_ID."007",'Unable to open RESULTS_'.$I.' file ');
		while(!feof($fp))
		{
			$line=stream_get_line($fp,10000,"\n");
			if ($line=="")continue;
			$tab=explode("\t",$line);
			/// and depending on the head, we put the result in gene
			if ($tab[0]=='GENE')
			{
				++$DBIDS['rna_gene_stat'];
				
				unset($tab[0]);
				
				fputs($fpO,$DBIDS['rna_gene_stat']."\t".implode("\t",$tab)."\n");
			}
			/// or in transcript
			else 
			{
				++$DBIDS['rna_transcript_stat'];;
				
				unset($tab[0]);
				fputs($fpT,$DBIDS['rna_transcript_stat']."\t".implode("\t",$tab)."\n");
			}
		}
		fclose($fp);
	}
	fclose($fpO);
	fclose($fpT);
	
addLog("Push gene statistics to rna_gene_stat");
	/// Once done, we push the data in the database
	$command='\COPY '.$GLB_VAR['DB_SCHEMA'].'.rna_gene_stat (rna_gene_stat_id,gene_seq_id,rna_tissue_id,n_sample,auc,lower_value,lr,min_value,q1,med_value,avg_value ,q3,max_value    ) FROM \''.'ALL_STAT_GENE.csv'."'  (DELIMITER E'\\t', null \\\"NULL\\\" ,format CSV )";
	echo $DB_INFO['COMMAND'].' -c "'.$command.'"'."\n";
	exec($DB_INFO['COMMAND'].' -c "'.$command.'"',$res,$return_code);
	print_r($res);
	
	if ($return_code !=0 )failProcess($JOB_ID."008",'Unable to insert '.$NAME); 
	

	
addLog("Push transcript statistics to rna_gene_stat");
	$command='\COPY '.$GLB_VAR['DB_SCHEMA'].'.rna_transcript_stat (rna_transcript_stat_id,transcript_id,rna_tissue_id,nsample,auc,lower_value,lr,min_value,q1,med_value,avg_value ,q3,max_value    ) FROM \''.'ALL_STAT_TR.csv'."'  (DELIMITER E'\\t', null \\\"NULL\\\" ,format CSV )";
	echo $DB_INFO['COMMAND'].' -c "'.$command.'"'."\n";
	exec($DB_INFO['COMMAND'].' -c "'.$command.'"',$res,$return_code);
	print_r($res);
	
	if ($return_code !=0 )failProcess($JOB_ID."009",'Unable to insert '.$NAME); 
				
	successProcess();

?>

