<?php

if (!defined("BIORELS")) header("Location:/");


/*

$MODULE_DATA['GENE_INFO']=$USER_INPUT['PORTAL']['DATA'];
$MODULE_DATA['GENE_LOCATION']=getGeneLocation($MODULE_DATA['GENE_INFO']['GENE_ID']);
$MODULE_DATA['RNA_EXPR']=getGeneGTEXExprStat($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);
$MODULE_DATA['TRANSCRIPTS']=getTranscriptStats($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);
$MODULE_DATA['ORTHOLOGS']=getOrthologs($MODULE_DATA['GENE_INFO']['GENE_ID'],true);
$MODULE_DATA['UNIPROT']=geneToUniprot($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);
$PRIM_UN=$MODULE_DATA['UNIPROT'][0]['PROT_IDENTIFIER'];
$MODULE_DATA['UNIPROT_DESC']=getUniprotDescription($PRIM_UN);
$MODULE_DATA['PATHWAY']=getPathwayStats($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);

 */

 
$PRIM_UN=$USER_INPUT['PORTAL']['DATA']['PROT_IDENTIFIER'];

$T=uniprotToGene($PRIM_UN);
if (isset($T[0]))
{
	$MODULE_DATA['GENE_INFO']=$T[0];
//print_r($MODULE_DATA['GENE_INFO']);exit;
$MODULE_DATA['GENE_LOCATION']=getGeneLocation($MODULE_DATA['GENE_INFO']['GENE_ID']);
$MODULE_DATA['UNIPROT_DESC']=getUniprotDescription($PRIM_UN);
$MODULE_DATA['PATHWAY']=getPathwayStats($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);
$MODULE_DATA['DRUGS']=getDrugGene($MODULE_DATA['GENE_INFO']['GN_ENTRY_ID']);
}
$MODULE_DATA['UNIPROT'][0]=$USER_INPUT['PORTAL']['DATA'];
$MODULE_DATA['PROT_NAME']=getUniprotNames($PRIM_UN);

global $USER_INPUT;

$TIME=array();$ts=microtime_float();

?>